# Documentation at http://goreleaser.com

# To do a release do, e.g.
# $ git tag -a v0.1.0 -m "First release"
# $ git push origin v0.1.0

# Then:
# $ source secrets.sourceme
# $ goreleaser --rm-dist

before:
  hooks: []
builds:
- env:
  - CGO_ENABLED=0
  goos:
    - linux
  goarch:
    - arm
  goarm:
    - 5
archive:
  replacements:
    darwin: Darwin
    linux: Linux
    windows: Windows
    386: i386
    amd64: x86_64
  files:
    - LICENSE
    - README.md
    - templates/**/*
checksum:
  name_template: 'checksums.txt'
snapshot:
  name_template: "{{ .Tag }}-next"
changelog:
  sort: asc
  filters:
    exclude:
    - '^docs:'
    - '^test:'
